### ISSUE TITLE
Программа падает

### ISSUE THREAD

**Issue by sergio-nsk** [ArtemGomer/ProgrammingNSU#16]
https://github.com/ArtemGomer/ProgrammingNSU/blob/a2f525447cdf197a4cf763993300b158c15c6766/Semester2/Lab5(Top-sort).c#L19

SEGV on unknown address 0x620efafb0ff8
The signal is caused by a WRITE memory access.

Я думаю, ты сам легко найдёшь причину падения.

**Comment by ArtemGomer** [comment]
Выход за массив?

**Comment by sergio-nsk** [comment]
А почему произошёл выход за массив?

**Comment by ArtemGomer** [comment]
Потому что не было проверки чтобы top был меньше 1001, я так думаю

**Comment by sergio-nsk** [comment]
Ответ не верный!
